/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DesktopNav: typeof import('./src/components/DesktopNav.vue')['default']
    LandingBtn: typeof import('./src/components/LandingBtn.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    PasswordInput: typeof import('./src/components/PasswordInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignOutBtn: typeof import('./src/components/SignOutBtn.vue')['default']
  }
}
